### PR TITLE
Add voice clone kidnapping story

### PR DESCRIPTION
**Pull request by milesmcc**

### CODE REVIEW

**Review by coderrg — CHANGES_REQUESTED** [review]
The precedent for this example is https://badness.ai/catalog/scammers-impersonating-son. I think `Cybercrime` would be a good fit for the category here (as opposed to `Impersonation`) since the category description fits well:

> Illegal activities committed using a computer or the internet, such as phishing attacks, scams, or identity theft, with the aim of stealing money or sensitive information.

**Comment by milesmcc** [comment]
It'd be both impersonation and cybercrime, right?

**Comment by milesmcc** [comment]
Oh, impersonation doesn't exist.

**Comment by milesmcc** [comment]
Good edits on the first paragraph; I made some more edits to the second.

**Comment by milesmcc** [comment]
(I don't think it's that important to focus on the people she was with; the point is that she was able to contact her husband and confirm that her daughter was safe.)

**Review by coderrg — APPROVED** [review]
Made a small grammar fix — if it looks good to you, feel free to merge!

**Pull request merged**
